name: Deploy RSS Feeds

on:
  # Optionally run on a schedule too:
  schedule:
    - cron: "0 0 * * *"  # runs daily at midnight
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # or your preferred version

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the feed script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python main.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GIT_TOKEN }}
          # The branch that hosts your site:
          publish_branch: gh-pages
          # The folder your script generated:
          publish_dir: ./output
